CITY_MAP = {
    "Воронеж": 270,
    "Екатеринбург": 628,
    "Ижевск": 194,
    "Йошкар-Ола": 284,
    "Москва": 16,
    "Новосибирск": 79,
    "Пермь": 80,
    "Ярославль": 361,
    "Белебей": 630,
    "Белорецк": 771,
    "Кумертау": 625,
    "Уфа": 254,
    "Агрыз": 72,
    "Азнакаево": 61,
    "Актаныш": 73,
    "Алексеевское": 86,
    "Альметьевск": 60,
    "Апастово": 50,
    "Арск": 51,
    "Бавлы": 63,
    "Балтаси": 52,
    "Буинск": 54,
    "Джалиль": 65,
    "Елабуга": 69,
    "Заинск": 74,
    "Зеленодольск": 70,
    "Казань": 14,
    "Кукмор": 58,
    "Лениногорск": 66,
    "Мензелинск": 75,
    "Муслюмово": 67,
    "Новошешминск": 87,
    "Нурлат": 88,
    "Чебоксары": 83,
    "Арзамас": 629,
    "Дзержинск": 626,
    "Тольятти": 603,
    "Саратов": 196,
}

CURRENCY_INDEX = {
    "bucks": "USD",
    "доллар": "USD",
    "даллар": "USD",
    "dollar": "USD",
    "бакс": "USD",
    "бач": "USD",
    "усд": "USD",
    "юсд": "USD",
    "usd": "USD",

    "евро": "EUR",
    "euro": "EUR",
    "eur": "EUR",

    "ag": "XAG",
    "xag": "XAG",
    "argentum": "XAG",
    "серебро": "XAG",
    "аргентум": "XAG",

    "au": "XAU",
    "xau": "XAU",
    "золото": "XAU",
    "злат": "XAU",
    "gold": "XAU",
    "голд": "XAU",

    "pd": "XPD",
    "xpd": "XPD",
    "палладий": "XPD",

    "pt": "XPT",
    "xpt": "XPT",
    "платина": "XPT",
}

CURRENCY_NAMES = {
    "USD": "Доллар (USD)",
    "EUR": "Евро (EUR)",
    "XAG": "Серебро (XAG)",
    "XAU": "Золото (XAU)",
    "XPD": "Палладий (XPD)",
    "XPT": "Платина (XPT)",
}


ACTION_INDEX = {
    "поменять": "office",
    "обменять": "office",
    "сменить": "office",
    "офис": "office",
    "отделение": "office",
    "банк": "office",

    "снять": "atm",
    "банкомат": "atm",
    "atm": "atm",

    "курс": "currency",
    "валюта": "currency",
}

BANK_SERVICES = {
    "ипотека": "mortgage.txt",
    "ипотеку": "mortgage.txt",
    "ипотеке": "mortgage.txt",
    "ипотекой": "mortgage.txt",
    "ипотеках": "mortgage.txt",
    "ипотек": "mortgage.txt",
    "ипотекам": "mortgage.txt",

    "вклад": "deposit.txt",
    "вклада": "deposit.txt",
    "вкладом": "deposit.txt",
    "вкладов": "deposit.txt",
    "вклады": "deposit.txt",
    "вкладами": "deposit.txt",
    "вкладах": "deposit.txt",

    "кредит": "credit.txt",
    "кредита": "credit.txt",
    "кредитом": "credit.txt",
    "кредиты": "credit.txt",
    "кредитах": "credit.txt",
    "кредитов": "credit.txt",

    "автокредит": "autocredit.txt",
    "автокредита": "autocredit.txt",
    "автокредитом": "autocredit.txt",
    "автокредиты": "autocredit.txt",
    "автокредитах": "autocredit.txt",
    "автокредитов": "autocredit.txt",
    "авто": "autocredit.txt",
    "автомобиль": "autocredit.txt",
    "автомобиля": "autocredit.txt",

    "бизнес": "business.txt",
    "бизнесе": "business.txt",
    "бизнеса": "business.txt",
    "бизнесом": "business.txt",
    "бизнесов": "business.txt",
    "бизнесам": "business.txt",
}
